spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #지연 로딩 성능 최적화를 위해 사용(in 쿼리 개수 설정 100 ~ 1000 권장)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace